---
#--------------------------------------------------------------#
# 0. Gather Facts Always                          [gather_facts]
#--------------------------------------------------------------#
- name: Gather Facts
  setup:
  tags: always
  when: ansible_facts == {}
#--------------------------------------------------------------#
# 1. Pre-checks                                 [node_prechecks]
#--------------------------------------------------------------#
- import_tasks: node_prechecks.yml

#--------------------------------------------------------------#
# 2. Pre-checks                                     [node_patch]
#--------------------------------------------------------------#
- import_tasks: node_patch.yml

#--------------------------------------------------------------#
# 3. Firewall                                    [node_firewall]
#--------------------------------------------------------------#
- import_tasks: node_firewall.yml

#--------------------------------------------------------------#
# 4. Packages                 [node_repo,node_pkg,node_packages]
#--------------------------------------------------------------#
- import_tasks: node_pkg.yml

#--------------------------------------------------------------#
# 5. Time                   [node_timezone, node_ntp, node_cron]
#--------------------------------------------------------------#
- import_tasks: node_time.yml

#--------------------------------------------------------------#
# 6. Admin                                          [node_admin]
#--------------------------------------------------------------#
- import_tasks: node_admin.yml
